--Inserts users
INSERT INTO 'user'(user_id,firstname,lastname,email,phone) VALUES ('23asdfs32','John','Doe','johndoe@gmail.com',6489465498);
INSERT INTO 'user'(user_id,firstname,lastname,email,phone) VALUES ('23asdfs32','John','Doe','johndoe@gmail.com',6489465498);
INSERT INTO 'user'(user_id,firstname,lastname,email,phone) VALUES ('23asdfs32','John','Doe','johndoe@gmail.com',6489465498);
INSERT INTO 'user'(user_id,firstname,lastname,email,phone) VALUES ('23asdfs32','John','Doe','johndoe@gmail.com',6489465498);
INSERT INTO 'user'(user_id,firstname,lastname,email,phone) VALUES ('23asdfs32','John','Doe','johndoe@gmail.com',6489465498);
INSERT INTO 'user'(user_id,firstname,lastname,email,phone) VALUES ('23asdfs32','John','Doe','johndoe@gmail.com',6489465498);


--Inserts some country data
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Afghanistan','93','AF','AFG');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Albania','355','AL','ALB');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Algeria','213','DZ','DZA');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('American Samoa','1-684','AS','ASM');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Andorra','376','AD','AND');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Angola','244','AO','AGO');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Anguilla','1-264','AI','AIA');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Antarctica','672','AQ','ATA');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Antigua and Barbuda','1-268','AG','ATG');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Argentina','54','AR','ARG');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Armenia','374','AM','ARM');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Aruba','297','AW','ABW');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Australia','61','AU','AUS');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Austria','43','AT','AUT');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Azerbaijan','994','AZ','AZE');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Bahamas','1-242','BS','BHS');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Bahrain','973','BH','BHR');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Bangladesh','880','BD','BGD');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Barbados','1-246','BB','BRB');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Belarus','375','BY','BLR');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Belgium','32','BE','BEL');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Belize','501','BZ','BLZ');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Benin','229','BJ','BEN');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Bermuda','1-441','BM','BMU');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Bhutan','975','BT','BTN');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Bolivia','591','BO','BOL');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Bosnia and Herzegovina','387','BA','BIH');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Botswana','267','BW','BWA');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Brazil','55','BR','BRA');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('British Indian Ocean Territory','246','IO','IOT');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('British Virgin Islands','1-284','VG','VGB');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Brunei','673','BN','BRN');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Bulgaria','359','BG','BGR');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Burkina Faso','226','BF','BFA');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Burundi','257','BI','BDI');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Cambodia','855','KH','KHM');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Cameroon','237','CM','CMR');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Canada','1','CA','CAN');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Cape Verde','238','CV','CPV');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Cayman Islands','1-345','KY','CYM');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Central African Republic','236','CF','CAF');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Chad','235','TD','TCD');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Chile','56','CL','CHL');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('China','86','CN','CHN');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Christmas Island','61','CX','CXR');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Cocos Islands','61','CC','CCK');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Colombia','57','CO','COL');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Comoros','269','KM','COM');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Cook Islands','682','CK','COK');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Costa Rica','506','CR','CRI');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Croatia','385','HR','HRV');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Cuba','53','CU','CUB');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Curacao','599','CW','CUW');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Cyprus','357','CY','CYP');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Czech Republic','420','CZ','CZE');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Democratic Republic of the Congo','243','CD','COD');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Denmark','45','DK','DNK');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Djibouti','253','DJ','DJI');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Dominica','1-767','DM','DMA');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Dominican Republic','1-809, 1-829, 1-849','DO','DOM');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('East Timor','670','TL','TLS');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Ecuador','593','EC','ECU');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Egypt','20','EG','EGY');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('El Salvador','503','SV','SLV');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Equatorial Guinea','240','GQ','GNQ');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Eritrea','291','ER','ERI');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Estonia','372','EE','EST');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Ethiopia','251','ET','ETH');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Falkland Islands','500','FK','FLK');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Faroe Islands','298','FO','FRO');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Fiji','679','FJ','FJI');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Finland','358','FI','FIN');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('France','33','FR','FRA');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('French Polynesia','689','PF','PYF');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Gabon','241','GA','GAB');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Gambia','220','GM','GMB');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Georgia','995','GE','GEO');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Germany','49','DE','DEU');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Ghana','233','GH','GHA');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Gibraltar','350','GI','GIB');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Greece','30','GR','GRC');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Greenland','299','GL','GRL');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Grenada','1-473','GD','GRD');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Guam','1-671','GU','GUM');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Guatemala','502','GT','GTM');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Guernsey','44-1481','GG','GGY');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Guinea','224','GN','GIN');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Guinea-Bissau','245','GW','GNB');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Guyana','592','GY','GUY');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Haiti','509','HT','HTI');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Honduras','504','HN','HND');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Hong Kong','852','HK','HKG');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Hungary','36','HU','HUN');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Iceland','354','IS','ISL');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('India','91','IN','IND');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Indonesia','62','ID','IDN');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Iran','98','IR','IRN');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Iraq','964','IQ','IRQ');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Ireland','353','IE','IRL');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Isle of Man','44-1624','IM','IMN');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Israel','972','IL','ISR');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Italy','39','IT','ITA');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Ivory Coast','225','CI','CIV');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Jamaica','1-876','JM','JAM');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Japan','81','JP','JPN');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Jersey','44-1534','JE','JEY');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Jordan','962','JO','JOR');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Kazakhstan','7','KZ','KAZ');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Kenya','254','KE','KEN');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Kiribati','686','KI','KIR');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Kosovo','383','XK','XKX');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Kuwait','965','KW','KWT');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Kyrgyzstan','996','KG','KGZ');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Laos','856','LA','LAO');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Latvia','371','LV','LVA');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Lebanon','961','LB','LBN');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Lesotho','266','LS','LSO');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Liberia','231','LR','LBR');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Libya','218','LY','LBY');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Liechtenstein','423','LI','LIE');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Lithuania','370','LT','LTU');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Luxembourg','352','LU','LUX');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Macau','853','MO','MAC');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Macedonia','389','MK','MKD');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Madagascar','261','MG','MDG');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Malawi','265','MW','MWI');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Malaysia','60','MY','MYS');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Maldives','960','MV','MDV');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Mali','223','ML','MLI');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Malta','356','MT','MLT');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Marshall Islands','692','MH','MHL');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Mauritania','222','MR','MRT');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Mauritius','230','MU','MUS');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Mayotte','262','YT','MYT');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Mexico','52','MX','MEX');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Micronesia','691','FM','FSM');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Moldova','373','MD','MDA');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Monaco','377','MC','MCO');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Mongolia','976','MN','MNG');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Montenegro','382','ME','MNE');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Montserrat','1-664','MS','MSR');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Morocco','212','MA','MAR');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Mozambique','258','MZ','MOZ');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Myanmar','95','MM','MMR');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Namibia','264','NA','NAM');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Nauru','674','NR','NRU');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Nepal','977','NP','NPL');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Netherlands','31','NL','NLD');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Netherlands Antilles','599','AN','ANT');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('New Caledonia','687','NC','NCL');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('New Zealand','64','NZ','NZL');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Nicaragua','505','NI','NIC');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Niger','227','NE','NER');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Nigeria','234','NG','NGA');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Niue','683','NU','NIU');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('North Korea','850','KP','PRK');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Northern Mariana Islands','1-670','MP','MNP');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Norway','47','NO','NOR');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Oman','968','OM','OMN');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Pakistan','92','PK','PAK');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Palau','680','PW','PLW');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Palestine','970','PS','PSE');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Panama','507','PA','PAN');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Papua New Guinea','675','PG','PNG');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Paraguay','595','PY','PRY');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Peru','51','PE','PER');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Philippines','63','PH','PHL');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Pitcairn','64','PN','PCN');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Poland','48','PL','POL');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Portugal','351','PT','PRT');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Puerto Rico','1-787, 1-939','PR','PRI');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Qatar','974','QA','QAT');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Republic of the Congo','242','CG','COG');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Reunion','262','RE','REU');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Romania','40','RO','ROU');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Russia','7','RU','RUS');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Rwanda','250','RW','RWA');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Saint Barthelemy','590','BL','BLM');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Saint Helena','290','SH','SHN');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Saint Kitts and Nevis','1-869','KN','KNA');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Saint Lucia','1-758','LC','LCA');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Saint Martin','590','MF','MAF');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Saint Pierre and Miquelon','508','PM','SPM');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Saint Vincent and the Grenadines','1-784','VC','VCT');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Samoa','685','WS','WSM');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('San Marino','378','SM','SMR');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Sao Tome and Principe','239','ST','STP');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Saudi Arabia','966','SA','SAU');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Senegal','221','SN','SEN');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Serbia','381','RS','SRB');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Seychelles','248','SC','SYC');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Sierra Leone','232','SL','SLE');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Singapore','65','SG','SGP');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Sint Maarten','1-721','SX','SXM');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Slovakia','421','SK','SVK');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Slovenia','386','SI','SVN');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Solomon Islands','677','SB','SLB');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Somalia','252','SO','SOM');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('South Africa','27','ZA','ZAF');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('South Korea','82','KR','KOR');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('South Sudan','211','SS','SSD');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Spain','34','ES','ESP');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Sri Lanka','94','LK','LKA');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Sudan','249','SD','SDN');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Suriname','597','SR','SUR');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Svalbard and Jan Mayen','47','SJ','SJM');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Swaziland','268','SZ','SWZ');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Sweden','46','SE','SWE');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Switzerland','41','CH','CHE');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Syria','963','SY','SYR');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Taiwan','886','TW','TWN');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Tajikistan','992','TJ','TJK');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Tanzania','255','TZ','TZA');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Thailand','66','TH','THA');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Togo','228','TG','TGO');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Tokelau','690','TK','TKL');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Tonga','676','TO','TON');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Trinidad and Tobago','1-868','TT','TTO');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Tunisia','216','TN','TUN');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Turkey','90','TR','TUR');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Turkmenistan','993','TM','TKM');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Turks and Caicos Islands','1-649','TC','TCA');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Tuvalu','688','TV','TUV');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('U.S. Virgin Islands','1-340','VI','VIR');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Uganda','256','UG','UGA');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Ukraine','380','UA','UKR');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('United Arab Emirates','971','AE','ARE');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('United Kingdom','44','GB','GBR');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('United States','1','US','USA');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Uruguay','598','UY','URY');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Uzbekistan','998','UZ','UZB');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Vanuatu','678','VU','VUT');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Vatican','379','VA','VAT');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Venezuela','58','VE','VEN');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Vietnam','84','VN','VNM');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Wallis and Futuna','681','WF','WLF');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Western Sahara','212','EH','ESH');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Yemen','967','YE','YEM');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Zambia','260','ZM','ZMB');
INSERT INTO country(country_name,phone_prefix,iso_code_1,iso_code_2) VALUES ('Zimbabwe','263','ZW','ZWE');


--Insert languages
INSERT INTO language(language) VALUES ('Acholi');
INSERT INTO language(language) VALUES ('Afar');
INSERT INTO language(language) VALUES ('Afrikaans');
INSERT INTO language(language) VALUES ('Akan');
INSERT INTO language(language) VALUES ('Akateko');
INSERT INTO language(language) VALUES ('Albanian');
INSERT INTO language(language) VALUES ('Amharic');
INSERT INTO language(language) VALUES ('Anuak');
INSERT INTO language(language) VALUES ('Apache');
INSERT INTO language(language) VALUES ('Arabic');
INSERT INTO language(language) VALUES ('Armenian');
INSERT INTO language(language) VALUES ('Assyrian');
INSERT INTO language(language) VALUES ('Azerbaijani');
INSERT INTO language(language) VALUES ('Bahasa');
INSERT INTO language(language) VALUES ('Bahdini');
INSERT INTO language(language) VALUES ('Bahnar');
INSERT INTO language(language) VALUES ('Bajuni');
INSERT INTO language(language) VALUES ('Bambara');
INSERT INTO language(language) VALUES ('Bantu');
INSERT INTO language(language) VALUES ('Barese');
INSERT INTO language(language) VALUES ('Basque');
INSERT INTO language(language) VALUES ('Bassa');
INSERT INTO language(language) VALUES ('Belorussian');
INSERT INTO language(language) VALUES ('Bemba');
INSERT INTO language(language) VALUES ('Benaadir');
INSERT INTO language(language) VALUES ('Bengali');
INSERT INTO language(language) VALUES ('Berber');
INSERT INTO language(language) VALUES ('Bosnian');
INSERT INTO language(language) VALUES ('Bravanese');
INSERT INTO language(language) VALUES ('Bulgarian');
INSERT INTO language(language) VALUES ('Burmese');
INSERT INTO language(language) VALUES ('Cantonese');
INSERT INTO language(language) VALUES ('Catalan');
INSERT INTO language(language) VALUES ('Cebuano');
INSERT INTO language(language) VALUES ('Chaldean');
INSERT INTO language(language) VALUES ('Chamorro');
INSERT INTO language(language) VALUES ('Chaochow');
INSERT INTO language(language) VALUES ('Chin Falam');
INSERT INTO language(language) VALUES ('Chin Hakha');
INSERT INTO language(language) VALUES ('Chin Mara');
INSERT INTO language(language) VALUES ('Chin Matu');
INSERT INTO language(language) VALUES ('Chin Senthang');
INSERT INTO language(language) VALUES ('Chin Tedim');
INSERT INTO language(language) VALUES ('Chipewyan');
INSERT INTO language(language) VALUES ('Chuukese');
INSERT INTO language(language) VALUES ('Cree');
INSERT INTO language(language) VALUES ('Croatian');
INSERT INTO language(language) VALUES ('Czech');
INSERT INTO language(language) VALUES ('Danish');
INSERT INTO language(language) VALUES ('Dari');
INSERT INTO language(language) VALUES ('Dewoin');
INSERT INTO language(language) VALUES ('Dinka');
INSERT INTO language(language) VALUES ('Duala');
INSERT INTO language(language) VALUES ('Dutch');
INSERT INTO language(language) VALUES ('Dzongkha');
INSERT INTO language(language) VALUES ('Edo');
INSERT INTO language(language) VALUES ('Ekegusii');
INSERT INTO language(language) VALUES ('English');
INSERT INTO language(language) VALUES ('Estonian');
INSERT INTO language(language) VALUES ('Ewe');
INSERT INTO language(language) VALUES ('Farsi');
INSERT INTO language(language) VALUES ('Fijian');
INSERT INTO language(language) VALUES ('Fijian Hindi');
INSERT INTO language(language) VALUES ('Finnish');
INSERT INTO language(language) VALUES ('Flemish');
INSERT INTO language(language) VALUES ('French');
INSERT INTO language(language) VALUES ('French Canadian');
INSERT INTO language(language) VALUES ('Fukienese');
INSERT INTO language(language) VALUES ('Fulani');
INSERT INTO language(language) VALUES ('Fuzhou');
INSERT INTO language(language) VALUES ('Ga');
INSERT INTO language(language) VALUES ('Gaddang');
INSERT INTO language(language) VALUES ('Gaelic-Irish');
INSERT INTO language(language) VALUES ('Gaelic-Scottish');
INSERT INTO language(language) VALUES ('Garre');
INSERT INTO language(language) VALUES ('Gen');
INSERT INTO language(language) VALUES ('Georgian');
INSERT INTO language(language) VALUES ('German');
INSERT INTO language(language) VALUES ('German Penn. Dutch');
INSERT INTO language(language) VALUES ('Gheg');
INSERT INTO language(language) VALUES ('Gokana');
INSERT INTO language(language) VALUES ('Greek');
INSERT INTO language(language) VALUES ('Gujarati');
INSERT INTO language(language) VALUES ('Gulay');
INSERT INTO language(language) VALUES ('Gurani');
INSERT INTO language(language) VALUES ('Haitian Creole');
INSERT INTO language(language) VALUES ('Hakka China');
INSERT INTO language(language) VALUES ('Hakka Taiwan');
INSERT INTO language(language) VALUES ('Hassaniyya');
INSERT INTO language(language) VALUES ('Hausa');
INSERT INTO language(language) VALUES ('Hawaiian');
INSERT INTO language(language) VALUES ('Hebrew');
INSERT INTO language(language) VALUES ('Hiligaynon');
INSERT INTO language(language) VALUES ('Hindi');
INSERT INTO language(language) VALUES ('Hindko');
INSERT INTO language(language) VALUES ('Hmong');
INSERT INTO language(language) VALUES ('Hunanese');
INSERT INTO language(language) VALUES ('Hungarian');
INSERT INTO language(language) VALUES ('Icelandic');
INSERT INTO language(language) VALUES ('Igbo');
INSERT INTO language(language) VALUES ('Ilocano');
INSERT INTO language(language) VALUES ('Indonesian');
INSERT INTO language(language) VALUES ('Inuktitut');
INSERT INTO language(language) VALUES ('Italian');
INSERT INTO language(language) VALUES ('Jakartanese');
INSERT INTO language(language) VALUES ('Jamaican Patois');
INSERT INTO language(language) VALUES ('Japanese');
INSERT INTO language(language) VALUES ('Jarai');
INSERT INTO language(language) VALUES ('Javanese');
INSERT INTO language(language) VALUES ('Jingpho');
INSERT INTO language(language) VALUES ('Jinyu');
INSERT INTO language(language) VALUES ('Juba Arabic');
INSERT INTO language(language) VALUES ('Jula');
INSERT INTO language(language) VALUES ('Kaba');
INSERT INTO language(language) VALUES ('Kamba');
INSERT INTO language(language) VALUES ('Kanjobal');
INSERT INTO language(language) VALUES ('Kannada');
INSERT INTO language(language) VALUES ('Karen');
INSERT INTO language(language) VALUES ('Kashmiri');
INSERT INTO language(language) VALUES ('Kayah');
INSERT INTO language(language) VALUES ('Kazakh');
INSERT INTO language(language) VALUES ('Kham');
INSERT INTO language(language) VALUES ('Khana');
INSERT INTO language(language) VALUES ('Khmer');
INSERT INTO language(language) VALUES ('K’iché');
INSERT INTO language(language) VALUES ('Kikuyu');
INSERT INTO language(language) VALUES ('Kimiiru');
INSERT INTO language(language) VALUES ('Koho');
INSERT INTO language(language) VALUES ('Korean');
INSERT INTO language(language) VALUES ('Krahn');
INSERT INTO language(language) VALUES ('Krio');
INSERT INTO language(language) VALUES ('Kunama');
INSERT INTO language(language) VALUES ('Kurmanji');
INSERT INTO language(language) VALUES ('Kyrgyz');
INSERT INTO language(language) VALUES ('Laotian');
INSERT INTO language(language) VALUES ('Latvian');
INSERT INTO language(language) VALUES ('Liberian Pidgin English');
INSERT INTO language(language) VALUES ('Lingala');
INSERT INTO language(language) VALUES ('Lithuanian');
INSERT INTO language(language) VALUES ('Luba-Kasai');
INSERT INTO language(language) VALUES ('Luganda');
INSERT INTO language(language) VALUES ('Luo');
INSERT INTO language(language) VALUES ('Maay');
INSERT INTO language(language) VALUES ('Macedonian');
INSERT INTO language(language) VALUES ('Malay');
INSERT INTO language(language) VALUES ('Malayalam');
INSERT INTO language(language) VALUES ('Maltese');
INSERT INTO language(language) VALUES ('Mam');
INSERT INTO language(language) VALUES ('Mandarin');
INSERT INTO language(language) VALUES ('Mandinka');
INSERT INTO language(language) VALUES ('Maninka');
INSERT INTO language(language) VALUES ('Manobo');
INSERT INTO language(language) VALUES ('Marathi');
INSERT INTO language(language) VALUES ('Marka');
INSERT INTO language(language) VALUES ('Marshallese');
INSERT INTO language(language) VALUES ('Masalit');
INSERT INTO language(language) VALUES ('Mbay');
INSERT INTO language(language) VALUES ('Mien');
INSERT INTO language(language) VALUES ('Mirpuri');
INSERT INTO language(language) VALUES ('Mixteco');
INSERT INTO language(language) VALUES ('Mizo');
INSERT INTO language(language) VALUES ('Mnong');
INSERT INTO language(language) VALUES ('Mongolian');
INSERT INTO language(language) VALUES ('Moroccan Arabic');
INSERT INTO language(language) VALUES ('Mortlockese');
INSERT INTO language(language) VALUES ('Napoletano');
INSERT INTO language(language) VALUES ('Navajo');
INSERT INTO language(language) VALUES ('Nepali');
INSERT INTO language(language) VALUES ('Ngambay');
INSERT INTO language(language) VALUES ('Nigerian Pidgin');
INSERT INTO language(language) VALUES ('Norwegian');
INSERT INTO language(language) VALUES ('Nuer');
INSERT INTO language(language) VALUES ('Nupe');
INSERT INTO language(language) VALUES ('Nyanja');
INSERT INTO language(language) VALUES ('Nyoro');
INSERT INTO language(language) VALUES ('Ojibway');
INSERT INTO language(language) VALUES ('Oromo');
INSERT INTO language(language) VALUES ('Pampangan');
INSERT INTO language(language) VALUES ('Papiamento');
INSERT INTO language(language) VALUES ('Pashto');
INSERT INTO language(language) VALUES ('Plautdietsch');
INSERT INTO language(language) VALUES ('Pohnpeian');
INSERT INTO language(language) VALUES ('Polish');
INSERT INTO language(language) VALUES ('Portuguese');
INSERT INTO language(language) VALUES ('Portuguese Brazilian');
INSERT INTO language(language) VALUES ('Portuguese Cape Verdean');
INSERT INTO language(language) VALUES ('Pugliese');
INSERT INTO language(language) VALUES ('Pulaar');
INSERT INTO language(language) VALUES ('Punjabi');
INSERT INTO language(language) VALUES ('Putian');
INSERT INTO language(language) VALUES ('Quechua');
INSERT INTO language(language) VALUES ('Quichua');
INSERT INTO language(language) VALUES ('Rade');
INSERT INTO language(language) VALUES ('Rakhine');
INSERT INTO language(language) VALUES ('Rohingya');
INSERT INTO language(language) VALUES ('Romanian');
INSERT INTO language(language) VALUES ('Rundi');
INSERT INTO language(language) VALUES ('Russian');
INSERT INTO language(language) VALUES ('Rwanda');
INSERT INTO language(language) VALUES ('Samoan');
INSERT INTO language(language) VALUES ('Sango');
INSERT INTO language(language) VALUES ('Seraiki');
INSERT INTO language(language) VALUES ('Serbian');
INSERT INTO language(language) VALUES ('Shanghainese');
INSERT INTO language(language) VALUES ('Shona');
INSERT INTO language(language) VALUES ('Sichuan Yi');
INSERT INTO language(language) VALUES ('Sicilian');
INSERT INTO language(language) VALUES ('Sinhala');
INSERT INTO language(language) VALUES ('Slovak');
INSERT INTO language(language) VALUES ('Slovene');
INSERT INTO language(language) VALUES ('Soga');
INSERT INTO language(language) VALUES ('Somali');
INSERT INTO language(language) VALUES ('Soninke');
INSERT INTO language(language) VALUES ('Sorani');
INSERT INTO language(language) VALUES ('Spanish');
INSERT INTO language(language) VALUES ('Sudanese Arabic');
INSERT INTO language(language) VALUES ('Sunda');
INSERT INTO language(language) VALUES ('Susu');
INSERT INTO language(language) VALUES ('Swahili');
INSERT INTO language(language) VALUES ('Swedish');
INSERT INTO language(language) VALUES ('Sylhetti');
INSERT INTO language(language) VALUES ('Tagalog');
INSERT INTO language(language) VALUES ('Taiwanese');
INSERT INTO language(language) VALUES ('Tajik');
INSERT INTO language(language) VALUES ('Tamil');
INSERT INTO language(language) VALUES ('Telugu');
INSERT INTO language(language) VALUES ('Thai');
INSERT INTO language(language) VALUES ('Tibetan');
INSERT INTO language(language) VALUES ('Tigré');
INSERT INTO language(language) VALUES ('Tigrigna');
INSERT INTO language(language) VALUES ('Toishanese');
INSERT INTO language(language) VALUES ('Tongan');
INSERT INTO language(language) VALUES ('Tooro');
INSERT INTO language(language) VALUES ('Trique');
INSERT INTO language(language) VALUES ('Turkish');
INSERT INTO language(language) VALUES ('Turkmen');
INSERT INTO language(language) VALUES ('Tzotzil');
INSERT INTO language(language) VALUES ('Ukrainian');
INSERT INTO language(language) VALUES ('Urdu');
INSERT INTO language(language) VALUES ('Uyghur');
INSERT INTO language(language) VALUES ('Uzbek');
INSERT INTO language(language) VALUES ('Vietnamese');
INSERT INTO language(language) VALUES ('Visayan');
INSERT INTO language(language) VALUES ('Welsh');
INSERT INTO language(language) VALUES ('Wodaabe');
INSERT INTO language(language) VALUES ('Wolof');
INSERT INTO language(language) VALUES ('Yemeni Arabic');
INSERT INTO language(language) VALUES ('Yiddish');
INSERT INTO language(language) VALUES ('Yoruba');
INSERT INTO language(language) VALUES ('Yunnanese');
INSERT INTO language(language) VALUES ('Zapoteco');
INSERT INTO language(language) VALUES ('Zarma');
INSERT INTO language(language) VALUES ('Zo');
INSERT INTO language(language) VALUES ('Zyphe');



--Inserts file 'file_type's
INSERT INTO 'file_type'(id,'type',extension) VALUES (1,'text','.txt');
INSERT INTO 'file_type'(id,'type',extension) VALUES (2,'json','.json');
INSERT INTO 'file_type'(id,'type',extension) VALUES (3,'pdf','.pdf');
INSERT INTO 'file_type'(id,'type',extension) VALUES (4,'java','.java');
INSERT INTO 'file_type'(id,'type',extension) VALUES (5,'xml','.xml');
INSERT INTO 'file_type'(id,'type',extension) VALUES (6,'word','.doc');
INSERT INTO 'file_type'(id,'type',extension) VALUES (7,'word','.docx');
INSERT INTO 'file_type'(id,'type',extension) VALUES (8,'excel','.xls');
INSERT INTO 'file_type'(id,'type',extension) VALUES (9,'excel','.xlsb');
INSERT INTO 'file_type'(id,'type',extension) VALUES (10,'excel','.xlsm');
INSERT INTO 'file_type'(id,'type',extension) VALUES (11,'excel','.xlsx');