app:
  datasource:
    main:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://192.168.100.204/jdbc-template-01
      username: johndoe
      password: johndoe@P4ssw()rd
      pool-size: 30

server:
  error:
    include-binding-errors: always
    include-message: always
