app.datasource.postgresql.driver-class-name=org.postgresql.Driver
app.datasource.postgresql.url=jdbc:postgresql://192.168.100.204:5432/jdbc-template-02
app.datasource.postgresql.username=johndoe
app.datasource.postgresql.password=johndoe@P4ssw()rd
app.datasource.postgresql.configuration.maximum-pool-size=30

app.datasource.mysql.driver-class-name=com.mysql.cj.jdbc.Driver
app.datasource.mysql.url=jdbc:mysql://192.168.100.204:3306/jdbc-template-02
app.datasource.mysql.username=johndoe
app.datasource.mysql.password=johndoe@P4ssw()rd
app.datasource.mysql.configuration.maximum-pool-size=30
app.datasource.derby.driver-class-name=org.apache.derby.jdbc.ClientDriver #For embedded use rg.apache.derby.jdbc.EmbeddedDriver
app.datasource.derby.url=jdbc:derby://192.168.100.204:1527/jdbc-template-02
app.datasource.derby.username=johndoe
app.datasource.derby.password=johndoe@P4ssw()rd
app.datasource.derby.configuration.maximum-pool-size=30
server.error.include-binding-errors=always
server.error.include-message=always
