server:
  port: 8080

spring:
  batch:
    initialize-schema: ALWAYS
    job:
      enabled: false

  # Note that AllowPublicKeyRetrieval=True could allow a malicious proxy
  # to perform a MITM attack to get the plaintext password,
  # so it is False by default and must be explicitly enabled.
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:toor8}
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/batch2?allowPublicKeyRetrieval=true&useSSL=false

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect