package springboot.samples.jwt02.domain;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.*;
import java.util.ArrayList;
import java.util.Collection;

@Data
@AllArgsConstructor
@NoArgsConstructor

@Entity
@Table(name="user")
public class AppUser {

    //Generation strategy=AUTO => id generated by orm
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;
    private String name;
    private String surname;
    private String username;
    private String password;

    //Eager load because I want to load all roles belonging to a user
    @ManyToMany(fetch= FetchType.EAGER)
    private Collection<AppRole> roles;


    public void addRole(AppRole role){
        if(roles==null)
            roles=new ArrayList<>();
        roles.add(role);
    }

}
