package springboot.samples.jwt02.domain;

import java.util.ArrayList;
import java.util.Collection;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor

@Entity
@Table(name = "user")
public class AppUser {

  //Generation strategy=AUTO => id generated by orm
  @Id
  @GeneratedValue(strategy = GenerationType.AUTO)
  private Long id;
  private String name;
  private String surname;
  private String username;
  private String password;

  //Eager load because I want to load all roles belonging to a user
  @ManyToMany(fetch = FetchType.EAGER)
  private Collection<AppRole> roles;


  public void addRole(AppRole role) {
    if (roles == null) {
      roles = new ArrayList<>();
    }
    roles.add(role);
  }

}
