services:
  mongo:
    container_name: mongo_cont
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=kafka-01
      - MONGO_INITDB_USERNAME=kafka-01-username
      - MONGO_INITDB_PASSWORD=kafka-01-password
      - MONGO-INITDB_ROOT_USERNAME=johndoe
      - MONGO-INITDB_ROOT_PASSWORD=johndoe@P4ssw()rd
    ports:
      - "27017":"27017"
    volumes:
      - mongodb-data:/data/mongodb-data
      - mongo-config:/data/configdb
    networks:
      - mongo_net

networks:
  mongo_net:
    driver: bridge

volumes:
  mongo-db-data:
  mongo-config: