services:
  postgres:
    container_name: postgres_cont
    image: postgres:latest
    environment:
      POSTGRES_USER: johndoe
      POSTGRES_PASSWORD: johndoe@P4ssw()rd
      PGDATA: /data/postgres
    volumes:
      - postgres_vol:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres_net
    restart: always

  mysql:
    container_name: mysql_cont
    image: mysql:8.0.28
    environment:
      MYSQL_USER: johndoe
      MYSQL_PASSWORD: johndoe@P4ssw()rd
      MYSQL_ROOT_PASSWORD: toor
    ports:
      - "3306:3306"
    volumes:
      - mysql_vol:/var/lib/mysql
    networks:
      - mysql_net
    restart: always

networks:
  postgres_net:
    driver: bridge
  mysql_net:
    driver: bridge

volumes:
  postgres_vol:
  mysql_vol:
